name: delivery_app
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  cloud_firestore: ^3.0.0
  cupertino_icons: ^1.0.3
  firebase_auth: ^3.1.2
  firebase_core: ^1.9.0
  flutter:
    sdk: flutter
  flutter_bloc: ^7.3.0
  font_awesome_flutter: ^9.1.0

   # Verificacion estado de red
  connectivity: ^3.0.6
  internet_connection_checker: ^0.0.1+3

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^1.0.4
  

flutter:
  uses-material-design: true
  assets:
    - assets/
